# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /blog/:year/:month/:day/:title/

# Setup
title:               Naoya Maruyama (丸山直也)
#tagline:             'A Jekyll theme'
description:         'HPC researcher at LLNL'
url:                 http://naoyam.github.io
baseurl:             ''
paginate:            5
paginate_path:	     "/blog/page:num/"
markdown:	     kramdown

# About/contact
author:
  name:              Naoya Maruyama
  url:               https://twitter.com/naoya_maruyama
  email:             naoya.maruyama@gmail.com

# Custom vars
#version:             1.0.0

plugins:
    - jekyll-paginate
    - jemoji
